### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by Crystal521** [AlexanderVeselov/RayTracing#1]
Hello,Alexander!
I have some questions to consult.If you are free.
When I compiled RayTracing on Opencl(Windows X64,NVIDIA),there are so many errors.I don't know how to solve them.Can you help me analyze it?Thank you!

![1](https://user-images.githubusercontent.com/12197955/26909452-84f1a10c-4c33-11e7-8733-f751addc4a54.jpg)

**Comment by AlexanderVeselov** [comment]
Hello! I suppose you you haven't specified the right paths in project properties (your cuda, opencl sdk and boost include and library directories):
![image](https://user-images.githubusercontent.com/17129401/27227590-bd1c968e-52ac-11e7-98b8-b63bff642202.png)
![image](https://user-images.githubusercontent.com/17129401/27227643-f7523cb4-52ac-11e7-9e4b-65f0f71969de.png)

**Comment by Crystal521** [comment]
Thank you for your reply!
I noticed that you've uploaded a new project about raytracing. So I tried this version. Sadly, there came up new problems. And my OpecnCL environment is AMD, it was available.
![results](https://user-images.githubusercontent.com/12197955/29003516-ec6fd6c4-7aea-11e7-91e8-cc2f873e2b89.png)
